variables:
    TEX_SOURCE_DIRECTORY: Thesis
    TEX_SOURCE: Thesis

include:
    -   local: '.gitlab/build-latex-document.gitlab-ci.yml'

stages:
    - build

build document:
    stage: build
    extends: .build-latex-document

    variables:
        TEX_PDF_NAME: Thesis-$CI_COMMIT_SHORT_SHA

build document for release:
    stage: build
    extends: .build-latex-document

    variables:
        TEX_PDF_NAME: Thesis-$CI_COMMIT_TAG

    rules:
        -    if: '$CI_COMMIT_TAG'
